### ISSUE TITLE
Guide to Being Happy with Emails

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/blog#122]
Some tips that have worked out well in the long-run:

- Unsubscribe from things. It's tempting to archive, but they'll come back. Unsubscribe every time. 
- Disable GitHub's auto-watch. Use a combination of email filters to hide emails that don't mention you explicitly. 
- Be OK with not answering every tweet, email, etc. 
- Ignore recruiters's emails (unless it serve your own purposes). I used to reply to each one, nah. 
- Turn off notifications for emails on your phone. You can still push/fetch them, but disable them on the lockscreen and badge.
- Treat email as completely asynchronous. It's OK if you mean to reply to something but leave it for a while. 

Gonna keep this around and add any more ideas that come to mind.

**Comment by imkevinxu** [comment]
Would love to read more about "Be OK with not answering every tweet, email, etc.".

I feel like I aspire to go above and beyond with being personal to everyone that reaches out to me but it's very "reactive" and is taking up more and more time

**Comment by ashfurrow** [comment]
Good advice, thanks! I think that's worth expanding on. The reactive part definitely resonates with me.
