### ISSUE TITLE
HTTPs should be the default way to access the site

### ISSUE THREAD

**Issue by KrauseFx** [ashfurrow/blog#171]
There is an option in CloudFlare to automatically redirect to https

via
https://twitter.com/KrauseFx/status/668462128349581312
https://twitter.com/KrauseFx/status/668474858905321473

**Comment by ashfurrow** [comment]
Figured this out in CloudFlare, in case anyone else needs to use https/ssl from CloudFlare serving a static site in an S3 bucket.

The setting is _not_ under "Crypto" like you might think, but I had to set up a Page Rule:

<img width="275" alt="screen shot 2015-11-22 at 4 27 53 pm" src="https://cloud.githubusercontent.com/assets/498212/11326373/097bfbc6-9136-11e5-9a01-3263ac10d4c1.png">

The pattern I used meant anything like gifs.ashfurrow.com or static.ashfurrow.com all get redirected to https. There was no change on S3 side.

Next step is to audit my site for any references to `http://ashfurrow.com/` and change it to the new protocol.
