### ISSUE TITLE
Problems with iOS Content Blockers

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/blog#184]
See: https://twitter.com/_brendonjustin/status/680943889700634624

TypeKit isn't falling back to the defaults like it should. 

/via @brendonjustin

**Comment by ashfurrow** [comment]
Weird, since I specify a CSS stack in _my_ CSS to fallback to other fonts, but that's not working. Reaching out to 1Blocker for advice.

**Comment by ashfurrow** [comment]
This blog post is some good reading: http://miranj.in/blog/2015/collateral-damage

I'm currently doing the "Flash Of Unstyled Text" method, which they recommend. They link to some other resources – I'll do some more reading.

**Comment by ashfurrow** [comment]
Hmm, couldn't reproduce with just 1Blocker. When I enabled both it and Crystal though, Safari hid the text once all fonts were downloaded.

**Comment by ashfurrow** [comment]
Actually, opening the log for the site with both content blockers enabled seems to show them fighting or something – just a constant stream of log messages indicating the same resources were being blocked over and over. 

1Blocker alludes to a problem with Safari using excessive battery while blocking custom fonts. If having two content blockers is related, then maybe having multiple rules enabled _within_ 1Blocker causes a similar problem. Going to shell out the 3.49 CAD to unlock their IAP to see.

**Comment by ashfurrow** [comment]
Ha, yeah, seeing the same "constant logging" behaviour when I have the setup from the tweet reporting the problem.

![2015-12-27 15_58_17](https://cloud.githubusercontent.com/assets/498212/12011961/b44c6f8a-acb2-11e5-81ca-38db7cdf5b83.gif)

**Comment by ashfurrow** [comment]
For anyone following along, the bug presents whenever both the "Custom Web Fonts" and "Block Twitter Widgets" are enabled.

**Comment by rinatkhanov** [comment]
Hey, 1Blocker team here. Thanks for the research, the issue was caused by a malfunctioning blocker rule inside "Block Twitter Widgets" package. This has been fixed in [v1.2](https://itunes.apple.com/app/id1025729002) which is out today. Sorry it took us so long.

**Comment by ashfurrow** [comment]
Hey @rinatkhanov thanks for getting back to me! Don't worry about it, glad you've got a fix out :bow:
