### ISSUE TITLE
Useless tags in RSS feed

### ISSUE THREAD

**Issue by Erikmitk** [ashfurrow/blog#186]
I use Feedbin to read your site via RSS and like I said [here](https://twitter.com/Erikmitk/status/683924961665376256) I noticed some superfluous wrapping paragraphs in some of your articles. I thought at first that it might be an issue with Feedbin since it doesn’t happen all the time, but I checked your feed.xml directly.

Those useless wrapper tags are in the form of

```XML
<p>BEGIN_WIDE</p>

…

<p>END_WIDE</p>
```
around block quotes, YouTube-embeds, Instagram-embeds and code sections. Also, YouTube embeds appear as

```XML
<p>BEGIN_WIDE</p>

YOUTUBE 6IUj6jyoTl0

<p>END_WIDE</p>
```

The feed.xml only goes back to 'Building My Career’ so I searched the cached articles in Feedbin for "BEGIN_WIDE" and the issue only appears to be in the following articles.

- Normalizing Struggle
- Building My Career
- Building Online Communities
- Putting a UICollectionView in a UITableViewCell in Swift

Additionally, it is not as consistent as I first thought. In 'Building My Career' only the Instagram-embed is affected but there’s no wrapping around block quotes. In the UICollectionView one the wrappers are around embedded images as well.

Maybe that helps you to identify the issue.

**Comment by ashfurrow** [comment]
Thanks for the issue! This appears related to the [embed plugin](https://github.com/ashfurrow/blog/blob/master/lib/embed.rb) and the [modify widths plugin](https://github.com/ashfurrow/blog/blob/master/lib/modify_widths.rb). Both of these are custom for my site. I imagine the fix will involve modifying the [feed builder](https://github.com/ashfurrow/blog/blob/2397a0ea91e85b7628102c1cafc69efcc52b5612/source/feed.xml.builder#L19) to use these extensions somehow. I'll have to look into the Middleman/builder docs. Thanks again!

**Comment by ashfurrow** [comment]
OK, I wrote a fix for this ^ It should deploy in a few minutes. Thanks again!
