### ISSUE TITLE
Normalizing Struggle Confirmed by Science

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/blog#193]
I wrote [this post](https://ashfurrow.com/blog/normalizing-struggle/) recently that I lay out how struggling is normal. 

Well, some [science happened](http://qz.com/622749/teens-do-better-in-science-when-they-know-einstein-and-curie-also-struggled/) and it turns out that I was right!

> After six weeks, the two groups who learned about how the scientists struggled significantly improved their science grades and increased their motivation to study science. The lowest performing students showed the greatest gains.
>
> Meanwhile, the students who learned only about the scientists’ achievements performed worse. They believed the scientists were innately gifted—unlike themselves.

I think this shows that not only is normalizing struggle beneficial for mental health and academics, but _failing_ to normalize struggle is actually harmful.

**Comment by mennenia** [comment]
This is awesome!!!! 

(more useful feedback shortly ^_^)

**Comment by mennenia** [comment]
This is awesome!!!! 

(more useful feedback shortly ^_^)
