### ISSUE TITLE
What would Ash do?

### ISSUE THREAD

**Issue by pbellot77** [ashfurrow/blog#258]
Hi Ash, my name is Patrick.(@pbellot on Twitter) I follow you and many other developers that are pushing the limits of Swift. I enjoy your insights and look forward to the posts you make about your work at Artsy. I'm a new developer that is hungry, passionate, and lucky enough to attempt to build apps. My question is, what would you do, with the knowledge you have today, if there were no tech companies where you lived? I'm a new unvalidated developer. Unvalidated because I have not made money or earned a wage developing, yet! I live in an area with 0 tech companies. I'm not sure what to do next. What would "today's Ash do" or "early career Ash" do?

**Comment by ashfurrow** [comment]
Hey there, thanks for the kind words and good question. I've documented my early career here: https://ashfurrow.com/blog/5-years-of-ios/ I'm wondering if that covers what you're looking for.

I also helped Orta discuss advice for early programmers in this blog post: http://artsy.github.io/blog/2016/01/30/iOS-Junior-Interviews/ Best of luck with everything!
