### ISSUE TITLE
Monospace font uses ligatures

### ISSUE THREAD

**Issue by ZevEisenberg** [ashfurrow/blog#298]
![screen shot 2017-01-20 at 6 54 26 pm](https://cloud.githubusercontent.com/assets/464574/22169437/0150facc-df42-11e6-99f3-f82410b40fa0.png)

From [this post](https://ashfurrow.com/blog/naming-things-in-swift/). Looks kinda weird. Definitely wouldn't want that enabled while coding. I didn't even know Menlo _had_ ligatures. `font-feature-settings: "liga" 0;` should work, but it didn't seem to when I tried it.

**Comment by ashfurrow** [comment]
Cool, thanks! Should be deployed shortly.

**Comment by ZevEisenberg** [comment]
Glad you figured out how to make it work. Web Inspector was having none of it.
