### ISSUE TITLE
Comparative Asynchronous Programming: FRP example

### ISSUE THREAD

**Issue by Thomvis** [ashfurrow/blog#302]
Thanks for the interesting article! 

I have a question/comment about the following code snippet:

```swift
getCredentialsFromUser()
  .flatMap { credentials in
    return login(with: credentials)
  }
  .on(next: { login in
      // Handle login success
    }, error: { error in
      // Handle login error
    })
```

Could it be that you want to use `subscribe(onNext:, onError:)` instead of the `on` operator? This would make it more equivalent to the Promises example right above that. Without a subscription, nothing will happen at all when this snippet runs. The `on` operator merely defines a side-effect of a subscription.

**Comment by ashfurrow** [comment]
Yeah, this is a fair point, thanks for letting me know! I'll amend the post.
