### ISSUE TITLE
Feed subdomain breaks relative links

### ISSUE THREAD

**Issue by HarshilShah** [ashfurrow/blog#359]
Since feeds are hosted with a [`feed` subdomain](https://github.com/ashfurrow/blog/blob/5f0c7b27bb7c03ed8d40251a40ae0bc1f007b890/data/site.yml), this breaks relative links to this site in RSS.

This could be solved either by expanding relative URLs [like with images](https://github.com/ashfurrow/blog/blob/17715983b36340320f8aee4b8bbb71e0a7b7fcfe/lib/custom_helpers.rb#L42) or removing the subdomain, whichever is preferable.

**Comment by ashfurrow** [comment]
Okay, fix is [deploying now](https://travis-ci.org/ashfurrow/blog/builds/355069079). Thanks again for pointing this out!

**Comment by HarshilShah** [comment]
Glad it’s fixed! 🙌🏽

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
