### ISSUE TITLE
Possible issue with 'as' usage

### ISSUE THREAD

**Issue by SeeThruHead** [ashfurrow/blog#367]
`const submission = this.state as ConsignmentSetup`

Is this a real thing you can do in JS? can't find any info about what it would even do.

**Comment by ashfurrow** [comment]
It is, in fact this is a line of code from our production app, which is open source:

https://github.com/artsy/emission/blob/365d34cba3bf96c74c6ae7f2615f37c82c669920/src/lib/Components/Consignments/Screens/Overview.tsx#L138

As I noted in the blog post, this is [TypeScript](https://www.typescriptlang.org), which adds data types to JavaScript and provides a level of compile-time certainty around the code we ship. I would not ship JavaScript without TypeScript, personally.

Hope that clears things up1

**Comment by SeeThruHead** [comment]
ah yes. ty
