### ISSUE TITLE
Move from <a> to <Link> 

### ISSUE THREAD

**Issue by orta** [ashfurrow/blog#406]
gatsby's Link is an `<a>` plus some magic which makes it even faster, you should only use it when linking internally. ( See the sidebar links in the v2 site https://www.typescriptlang.org/v2/docs/handbook/release-notes/typescript-3-2.html ) 

So:
 - any nav = Link
 - then for the internal links in the markdown, I use [gatsby-plugin-catch-links](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-catch-links)

**Comment by ashfurrow** [comment]
Awesome, thanks! One note is that I should _not_ link to search using Link, because Gatsby will pre-download the entire search index on every page 😅
