### ISSUE TITLE
Image caching

### ISSUE THREAD

**Issue by bre7** [ashfurrow/blog#408]
Hey Ash, casual blog reader here !

Quick suggestion: would you consider caching the `static` dir contents (as per https://www.gatsbyjs.org/docs/caching/#static-files).

IIRC Netlify works similar to Firebase:

```json
"headers": [
  {
    "source": "static/**/*",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  }
]
```

**Comment by ashfurrow** [comment]
Oh, what a good idea! Any reason to close the issue? I’ll try to get on this.

**Comment by bre7** [comment]
I'm not sure now if it's needed: isn't gatsby's offline plugin performing caching on it's own ?

**Comment by ashfurrow** [comment]
Ah gotcha! I [checked the docs](https://www.gatsbyjs.org/docs/caching/) and you're right. They also suggest that plugin, which I'm using already:

https://github.com/ashfurrow/blog/blob/aeee9620444d10c1af4a874af8728a1a5f570e1a/gatsby-config.js#L256-L261

So I think this should be covered. Thanks again!

**Comment by bre7** [comment]
`gatsby-plugin-netlify-cache` != `gatsby-plugin-netlify`


The first one is intended for build caching whilst the second one adds the intended HTTP headers ! I got them mixed up at first:

- https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cache/
- https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/
