### ISSUE TITLE
Gives me an error in yarn start

### ISSUE THREAD

**Issue by talmax1124** [ashfurrow/blog#444]
Gives me this error:

warn code block or inline code language not specified in markdown. applying generic code block
warn unable to find prism language 'sh' for highlighting. applying generic code block

 ERROR 

Gatsby-plugin-sharp wasn't setup correctly in gatsby-config.js. Make sure you add it to the plugins array.

not finished source and transform nodes - 22.805s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blog@1.0.0 start: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blog@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/carlosdiazplaza/.npm/_logs/2021-02-09T02_13_28_212Z-debug.log
Waiting for the debugger to disconnect...

**Comment by ashfurrow** [comment]
Hmm, that's weird. The warning is fine, I see it on my computer too. Does `yarn install` succeed okay? I would also try:

```sh
rm -rf node_modules
yarn install
```

To see if that fixes it. 

What operating system are you using? macOS looks like?
