### ISSUE TITLE
More photography/sketching followup

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/blog#83]
I've heard that everyone is born a sketcher – that we all drawn as children – until we reach a certain age where we realize that our drawings don't reflect reality, that we lack the skill to produce something "good." But what is good?

![](http://threepanelsoul.com/comics/2014-08-19-336.png)

Why do children draw? Because it's fun. It has value to them not because of the drawing when its finished, but because the act of drawing – the act of self-expression – is a fulfilling activity. As adults, why do we ignore this truth? Why do we place to much emphasis on what a drawing or painting or photograph _looks_ like? 

I realized last year that I don't really care about my photographs, that I only really care about my photography. The photos I make are valuable _only_ in their relation to the act of creating them. 

This gets to the heart of the problem: we place an enormous emphasis on the skill involved in making art. This can be seen throughout art history, like when pointillism was first shunned by mainstream art critics because it didn't accurately reflect the way the world actually looked [citation needed]. It was unrealistic, so it was bad. 

But pointillism is incredibly valuable, and the paintings that came out of that era are some of the most famous in the world. 

![](http://innisdale.ca/CyberARTS2015/wp-content/uploads/2014/11/Simpsons-Sunday-Afternoon.jpg)

![](https://s-media-cache-ak0.pinimg.com/originals/74/07/34/7407346a8cf2108c20163ef2596adcad.jpg)

Art can be valuable without skill, and it can be worthless with skill. [Insert a few examples of my own work, say, a boring film photograph that shows skill vs an interesting instagram photo].

Art, to me, is about self-expression. The evaluated "good" that society places on it is only a proxy for its true value, to that of the artist.

**Comment by ashfurrow** [comment]
This is really a pipeline problem – we need to stop children from devaluing their artwork because it doesn't reflect reality. Picasso said:

> It took me four years to paint like Raphael, but a lifetime to paint like a child.

**Comment by orta** [comment]
I think there's a period in which everyone goes though ( you should ask jessica about this, I think I've talked to her on this.) In that:
* You start liking pure representationalism, get bored of landscapes/portraits.
* Then move to conceptualism, this is where you & I am, you think art is about ideas and context.
* Finally you end up liking really old old stuff like renaissance art again

I'm not sure most people get past stage one TBH, not sure I would have had I not started working at artsy.

**Comment by ashfurrow** [comment]
Fixed in https://github.com/ashfurrow/blog/commit/e24e2eb7e73f38d435909777d2ebe155e2c56361
