### ISSUE TITLE
Redesign speaking page

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/blog#9]
It looks OK but isn't great – especially the big list of talks with italics text – very difficult to read.

**Comment by ashfurrow** [comment]
Gonna work with @AshleyKrista on this one. Ideas so far:

- Integrate a world map with places I've spoken at – maybe interactive?
- Focus more heavily on upcoming talks instead of weighting old ones/new ones evenly. 
- Embed content like instagram photos or videos of me speaking to demonstrate that I'm not just some madman speaking to empty rooms. 

Maybe others. The new page should serve three functions, in decreasing order of importance:

1. Establish my credentials as a speaker.
1. Convince conference organizers to invite me to their awesome conference.
1. Provide resources from previous talks for people who are looking for slides, code examples, and videos.

**Comment by ashfurrow** [comment]
![speaking](https://cloud.githubusercontent.com/assets/498212/7445357/49c8ba06-f1af-11e4-90fc-a7cb6237da16.png)

**Comment by ashfurrow** [comment]
The columns for talks are going to be a bit wider than shown (like the portfolio page). Other than that, I like this.

**Comment by AshleyKrista** [comment]
Yeah grounding. exactly :D
