### ISSUE TITLE
Career

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/blog#96]
Starting to think about it more, especially after talking with @dblock a few weeks ago. Where am I going? Why? What is comfortable and what is scary? 

A good discussion would include references to [Artsy's compensation framework](https://artsy.github.io/blog/2015/04/03/artsy-engineering-compensation-framework/), reflections on why it might be structured the way it is, why parts of it I'm excited about following (or not), and why.

**Comment by dblock** [comment]
I am really curious to see where this goes, happy to discuss too!
