### ISSUE TITLE
Cloudy Conway

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/blog#99]
![Can't stop favouriting these](https://cloud.githubusercontent.com/assets/498212/8754394/404463dc-2c91-11e5-8688-b40e6534255c.png)

https://twitter.com/CloudyConway/status/622055867098206208

https://twitter.com/CloudyConway/

**Comment by AshleyKrista** [comment]
So kewl

**Comment by ashfurrow** [comment]
http://www.vexorian.com/2015/05/cloudy-conway.html

The source will be open soon – might wait for that.

**Comment by ashfurrow** [comment]
Once again, I forget to use commit messages to close issues. 

Fixed in https://github.com/ashfurrow/blog/commit/eaca95233b03333442d5944cb34726027ba4193f
